version: 2.1
jobs:
  vue-dashboard:
    working_directory: ~/vue-dashboard/vue-dashboard
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout:
          path: ~/vue-dashboard
      - node/install:
          install-npm: false
          install-yarn: true
          node-version: latest
      - node/install-packages:
          cache-key: yarn.lock
          app-dir: ~/vue-dashboard/vue-dashboard
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn build
orbs:
  node: circleci/node@2.0.3
workflows:
  vue-dashboard:
    jobs:
      - vue-dashboard
